theme: jekyll-theme-merlot
title: Zhelnov to Editors
description: An open letter to editors of medical journals by Pavel Zhelnov about his Russian translation of the PRISMA 2020 Statement.
show_downloads: "false"
google_analytics: UA-122303329-4
