theme: jekyll-theme-merlot
google_analytics: UA-122303329-4
show_downloads: false
includes_dir: .
lang: en
author:
  twitter: drzhelnov
  picture: /assets/images/pavelzhelnov.jpg
twitter:
  username: drzhelnov
  card: summary
facebook:
  admins: 4553361461371192
logo: /assets/images/pavelzhelnov.jpg
social:
  name: Pavel Zhelnov
  links:
    - https://twitter.com/drzhelnov
    - https://www.facebook.com/drzhelnov
    - https://www.linkedin.com/in/pavel-zhelnov-382073182
    - https://github.com/pussiatoday
    - http://scholar.google.com/citations?user=b421BNkAAAAJ
    - http://orcid.org/0000-0003-2767-5123
    - https://researchgate.net/profile/Pavel_Zhelnov
    - https://osf.io/9c83x/
    - https://t.me/drzhelnov
title: Zhelnov to Editors
description: An open letter to editors of medical journals by Pavel Zhelnov about his Russian translation of the PRISMA 2020 Statement.
header:
  en: Zhelnov to Editors
  ru: Желнов — редакторам
headline:
  en: An open letter from Pavel Zhelnov to editors of medical journals about his Russian translation of the PRISMA 2020 Statement.
  ru: Открытое письмо от Павла Желнова редакторам медицинских журналов о русском переводе заявления PRISMA 2020.
generated-with:
  en: Generated with
  ru: Произведено при помощи
using:
  en: using
  ru: с использованием
support:
  en: "Help fund the translation:"
  ru: "Помочь профинансировать перевод:"
share:
  en: "Share the link to this letter:"
  ru: "Поделиться ссылкой на это письмо:" 
progress:
  en: "Funds raised for the translation:"
  ru: "Собрано средств на перевод:"
currency:
  en: USD
  ru: "руб."
data-max:
  en: 700
  ru: 56000
data-value:
  en: 0.01
  ru: 0.01
